Assign record value dynamically in Apex
beyond-the-cloud-dev/salesforce-tips pull request #11
Opened 2023-11-09 08:25 UTC by pgajek2

2023-11-10 09:45 UTC, osieckiAdam requested changes
1. Przydałoby się żeby kod na drugim slajdzie był mniej więcej równej wielkości, to są podobne ilości kodu a pierwszy snippet jest wyraźnie mniejszy, jest przestrzeń do sprawienia jeszcze lepszego wrażenia wizualnego
2. Można by było opatrzyć też te snippety jakimś słowem komentarza, zamysł jest oczywiście jasny bo wszystko elegancko wytłumaczone na pierwszym slajdzie ale tutaj brak czegokolwiek poza kodem sprawia wrażenie jakby był niedokończony albo coś się nie zrenderowało

2023-11-10 09:56 UTC, janeksledziewski commented
Brakuje opisu, co się dzieje na drugiej stronie. Piszesz o metodach `put` a na drugiej stronie tylko raz użyta + fragment z TDF, który na pierwszy rzut oka nie odnosi się do tego.

2023-11-10 09:57 UTC, janeksledziewski requested changes
2. Stronka zmiany w komentarzu wyżej.

2023-11-10 10:33 UTC, janeksledziewski requested changes
Dalej nie wiem, o co chodzi ci z tym TDF, za mało łopatologicznie.

2023-11-10 10:37 UTC, pgajek2 commented
> Dalej nie wiem, o co chodzi ci z tym TDF, za mało łopatologicznie.

To co byś Janku napisał?

2023-11-23 07:37 UTC, janeksledziewski approved these changes

2023-12-20 18:13 UTC, merged