Throw Apex built-in exceptions
beyond-the-cloud-dev/salesforce-tips pull request #3
Opened 2023-10-30 08:48 UTC by pgajek2

BeyondTheCloud: Salesforce Tips & Tricks ☁
10: Throw Apex built-in exceptions
[#beyondTheCloudTips](https://www.linkedin.com/feed/hashtag/?keywords=beyondthecloudtips)

2023-10-30 09:12 UTC, niou-ns reviewed
a AuraHandledException? 🦧

2023-10-30 09:26 UTC, osieckiAdam reviewed
A tutaj to bym zaprosił do dyskusji, bo moim zdaniem to jest bardziej temat na posta.
Sama informacja że można to zrobić to jest 20% sukcesu, ale pytanie czy powinno się to robić? A jeżeli tak to dlaczego? Bo moim zdaniem w większości przypadków to jest anti-pattern, no na przykład to rzucanie Limit Exceptionów, to by było szaleństwo i dobrze że tam chociaż dopisałeś że nie można ich catchować
Znacie jakieś use-casy gdzie warto wstawić systemowe exceptiony zamiast customowych? bo mi to trochę na pierwszy rzut oka śmierdzi curry i oszczędzaniem na literkach w kodzie

To mi trochę przypomniało jak jakiś ziomek w Motoroli mówił że można sobie robić asserty w kodzie produkcyjnym zamiast null checków. No można, można też chodzić po klockach lego bosymi stopami zamiast kłaść sobie miękki dywanik w łazience

2023-10-30 09:31 UTC, pgajek2 commented
> A tutaj to bym zaprosił do dyskusji, bo moim zdaniem to jest bardziej temat na posta. Sama informacja że można to zrobić to jest 20% sukcesu, ale pytanie czy powinno się to robić? A jeżeli tak to dlaczego? Bo moim zdaniem w większości przypadków to jest anti-pattern, no na przykład to rzucanie Limit Exceptionów, to by było szaleństwo i dobrze że tam chociaż dopisałeś że nie można ich catchować Znacie jakieś use-casy gdzie warto wstawić systemowe exceptiony zamiast customowych? bo mi to trochę na pierwszy rzut oka śmierdzi curry i oszczędzaniem na literkach w kodzie
> 
> To mi trochę przypomniało jak jakiś ziomek w Motoroli mówił że można sobie robić asserty w kodzie produkcyjnym zamiast null checków. No można, można też chodzić po klockach lego bosymi stopami zamiast kłaść sobie miękki dywanik w łazience

Przykład w SOQL Lib xd aby zachowanie było takie samo jak przy zwykłym SOQL ale handlować nulle.
<img width="696" alt="image" src="https://github.com/beyond-the-cloud-dev/salesforce-tips/assets/23002099/4aee6142-5f8a-4e66-b20d-bee6a7ea8085">

Można by podpytać tutaj czy ma to sens: https://salesforce.stackexchange.com/questions/111419/can-built-in-exceptions-be-thrown

2023-10-30 09:32 UTC, niou-ns approved these changes
Spryciula jak to wplótł w tekst!

2023-10-30 09:32 UTC, osieckiAdam commented
Wyobraźmy sobie teraz takiego modelowego, hipotetycznego hindusa który ma mało rozumku ale jest ambitny, czyta posty i inspiruje się BTC bo chce zostać Wielkim Programistą
Przeczyta tego tipa i od jutra na Code Review będzie wypierdalał custom exceptiony i kazał robić jakieś systemowe.

Na przykład wyobrażam sobie taką sytuację, że do obsługi błędnego inputu każe wypierdolić custom exception i każe wstawić StringException co by było głupie, no bo to jest błędny string, a właśnie zajebistym przykładem jest to co napisałeś bo ja jedyny use case widzę właśnie w momencie gdy rozszerzamy albo wrapujemy standardowe rzeczy i analogicznie jeżeli dałoby się extendować albo nadpisywać klasę String to wtedy to by było miejsce na StringException, albo tak jak pokazujesz wrapper na standardowe SOQLe

2023-10-31 12:07 UTC, janeksledziewski commented
Moim zdaniem, czasem warto posłużyć się wbudowanym exceptionem, np walidacja inputu, po co tam robić custom jak możesz jakimś standardem rzucić, np. InvalidParamenterValue lub NullPointer jak nie ma. Też spotkałem się z kodem, który sprawdzał dostęp usera i rzucał LimitException po to żeby na pewno nie dało się przejść dalej.

2023-10-31 12:08 UTC, janeksledziewski requested changes

2023-10-31 12:08 UTC, janeksledziewski commented on Throw Apex built-in exceptions.pdf
Add a reference doc: https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_classes_exception_methods.htm

2023-11-06 15:00 UTC, pgajek2 commented on Throw Apex built-in exceptions.pdf
To jest dobre!!!

2023-11-07 09:31 UTC, merged